# Generated by Django 5.2.5 on 2025-08-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="description",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
